services:
  web:
    image: bazigan/myweb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    init: true
    volumes:
      - web-data:/usr/share/nginx/html
    scale: 3

volumes:
  web-data: {}