services:
  web:
    image: bazigan/myweb:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    init: true
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1